spring:
  servlet:
    multipart:
      #单个文件的最大值
      max-file-size: 5MB
      #上传文件的最大值
      max-request-size: 5MB
  resources:
    #增加外部静态资源目录映射
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:\File\
webvalue:
  resourcePath: D:\File\